---
title: "Fifa 19 EDA"
output: html_notebook
---

```{r Libraries}
library(tidyverse)
library(cowplot)
library(dplyr)
library(ggplot2)
library(maps)
library(highcharter)
```



```{r}
df1 = read.csv("data.csv")
summary(df1)

```


```{r}
Original_df1 <- df1

Fixed_df1 <- Original_df1 %>% 
  mutate(
    Value = case_when(
      grepl("M", df1$Value) ~ as.numeric(substring(df1$Value, 2, nchar(as.character(df1$Value))-1)) * 1000000,
      grepl("K", df1$Value) ~ as.numeric(substring(df1$Value, 2, nchar(as.character(df1$Value))-1)) * 1000,
      TRUE ~ as.numeric(df1$Value)
    ),
    Wage = case_when(
      grepl("M", df1$Wage) ~ as.numeric(substring(df1$Wage, 2, nchar(as.character(df1$Wage))-1)) * 1000000,
      grepl("K", df1$Wage) ~ as.numeric(substring(df1$Wage, 2, nchar(as.character(df1$Wage))-1)) * 1000,
      TRUE ~ as.numeric(df1$Wage)
    ),
    Release.Clause = case_when(
      grepl("M", df1$Release.Clause) ~ as.numeric(substring(df1$Release.Clause, 2, nchar(as.character(df1$Wage))-1)) * 1000000,
      grepl("K", df1$Release.Clause) ~ as.numeric(substring(df1$Release.Clause, 2, nchar(as.character(df1$Wage))-1)) * 1000,
      TRUE ~ as.numeric(df1$Release.Clause)
    )   
)
    
df1$Value=Fixed_df1$Value
df1$Wage=Fixed_df1$Wage
df1$Release.Clause=Fixed_df1$Release.Clause

cat('Converted into integer ')


```


```{r}
head(df1$Value)
head(df1$Wage)
```

```{r}
summary(df1$Overall)
hchart(df1$Overall, name = 'Overall Rate')
```

```{r}
summary(df1$Preferred.Foot)
hchart(df1$Preferred.Foot, name = 'Preferred.Foot')
```


```{r}
summary(df1$Value)

hcboxplot(x = df1$Overall, var = df1$Value) %>%
  hc_chart(type = "column") %>%
  hc_yAxis(title = list(text = "Overall Rate"),
       labels = list(format = "{value}")) %>%
  hc_xAxis(title = list(text = "Value"),
       labels = list(format = "{value}"), max = 100)  

```


```{r}
players__Top_Valued <- df1 %>%
    select(Name, Nationality, Overall, Value, Wage)%>%
    group_by(Value)%>%
    arrange(desc(Value))%>%
    head(10)
data.frame(players__Top_Valued)   
```



```{r}
require(scales)
players_plot <- df1 %>%
    group_by(Value)%>%
    arrange(desc(Value))%>%
    head(10)%>%
    ggplot(mapping = aes(x = Name, y = Value, color = Nationality, fill = Nationality, alpha = Value, size=Value))+
    geom_bar(stat='identity')+
    coord_polar()+
    theme_minimal()+
    labs(x = 'Name', y ='Value', title ='Highest Valued Players')+
    theme(plot.title = element_text(hjust=0.5),legend.position ='bottom')+
    scale_y_continuous(labels = comma)
    
players_plot



```


```{r}
overall_data <- df1 %>% 
  group_by(Nationality) %>% 
  summarise(Count = n(), 
            Avg_Potential = mean(Potential)) %>%
  filter(Count > 50)

overall_data %>%
    select(Nationality, Avg_Potential)%>%                       
    arrange(desc(Avg_Potential)) 
worldmap = map_data("world")                           
merged_data <- merge(x = worldmap, y = overall_data, by.x = "region", by.y = "Nationality", all.x = TRUE) %>% arrange(order)
ggplot(data = merged_data, aes(x = long, y = lat, group = group)) +
  geom_polygon(aes(fill = Avg_Potential)) +
  labs(fill='Average Potential')
```
The following lines of code are for Week 2 Group Assignment. 


```{r Preliminary steps to implement ML}

#Converting 'M' and 'K' into 10^6 and 10^3  

df1 <- df1 %>% mutate(multiplier = ifelse(str_detect(Value, "K"), 1000, ifelse(str_detect(Value, "M"), 1000000, 1))) 
df1 <- df1 %>% mutate(Value = as.numeric(str_extract(Value, "[0-9]+")) * multiplier)

#Converting 6'0 into 72 inches
df1 <- df1 %>% mutate(Weight = as.numeric(str_extract(Weight, "[0-9]+")))
df1 <- df1 %>% mutate(Height = as.numeric(str_extract(Height, "[0-9]+"))*12 + as.numeric(str_extract(Height, "[0-9]+$")))


#Grouping the players into 4 categories : Goalkeeper, Defender, Midfielder, Forward. 
positions <- unique(df1$Position)

gk <- "GK"
defs <- positions[str_detect(positions, "B$")]
mids <- positions[str_detect(positions, "M$")]
fwds <- positions[str_detect(positions, "F$|S$|T$|W$")]

df1 <- df1 %>% mutate(PositionGroup = ifelse(Position %in% gk, "GK", ifelse(Position %in% defs, "DEF", 
                ifelse(Position %in% mids, "MID", ifelse(Position %in% fwds, "FWD", "Unknown")))))

myvars2 <- c('Value', 'Overall', 'Height', 'Weight', 'Crossing', 'Finishing', 'HeadingAccuracy', 
            'ShortPassing', 'Volleys', 'Dribbling', 'Curve', 'FKAccuracy', 'LongPassing', 'BallControl', 'Acceleration', 'SprintSpeed', 
             'Agility', 'Reactions', 'Balance', 'ShotPower', 'Jumping', 'Stamina', 'Strength', 'LongShots', 'Aggression', 
             'Interceptions', 'Positioning', 'Vision', 'Penalties', 'Composure', 'Marking', 'StandingTackle', 'SlidingTackle', 
             'GKDiving', 'GKHandling', 'GKKicking', 'GKPositioning', 'GKReflexes', 'PositionGroup')
```


```{r Dividing Dataset in 2 parts}
df1 <- df1[myvars2]
fifadf.gk <- sample_n(subset(df1, PositionGroup == 'GK'), 1000)
fifadf.outfield <- sample_n(subset(df1, PositionGroup != 'GK'), 5000)
```


```{r Tree GK}
#tree gk
library (tree)

#dividing the dataset into training and test sets. 
train.gk <- sample(1:nrow(fifadf.gk), nrow(fifadf.gk)/2)
fifadf.gk.test <- fifadf.gk[-train.gk, 'Overall']

#creating the regression tree
tree.fifadf.gk <- tree(Overall ~ . -(Value+PositionGroup), data = fifadf.gk)

#summary(tree.fifadf.gk)
plot(tree.fifadf.gk)
text(tree.fifadf.gk , pretty =0)

yhat.tree.gk <- predict(tree.fifadf.gk, newdata = fifadf.gk[-train.gk,])
cat('The mean squared error is ', mean((yhat.tree.gk - fifadf.gk.test)^2))
```


```{r Tree Outfield}
#tree outfield
train.outfield <- sample(1:nrow(fifadf.outfield), nrow(fifadf.outfield)/2)
fifadf.outfield.test <- fifadf.outfield[-train.outfield, 'Overall']

tree.fifadf.outfield <- tree(Overall ~ . -(Value+PositionGroup), data = fifadf.outfield)

#summary(tree.fifadf.outfield)

plot(tree.fifadf.outfield)
text(tree.fifadf.outfield , pretty =0)

yhat.tree.outfield <- predict(tree.fifadf.outfield, newdata = fifadf.outfield[-train.outfield,])
cat('The mean squared error is ', mean((yhat.tree.outfield - fifadf.outfield.test)^2))
```


```{r RandomForest GK}
#RandomForest gk
library(randomForest)

bag.fifadf.gk <- randomForest(Overall ~ . -(Value+PositionGroup), data = fifadf.gk, subset = train.gk, importance = TRUE)

#importance(bag.fifadf.gk)
varImpPlot(bag.fifadf.gk, n.var=10)

yhat.bag.gk <- predict(bag.fifadf.gk, newdata = fifadf.gk[-train.gk, ])
cat('The mean squared error is ', mean((yhat.bag.gk - fifadf.gk.test)^2))
```


```{r RandomForest Outfield}
#RandomForest outfield

bag.fifadf.outfield <- randomForest(Overall ~ . -(Value+PositionGroup), data = fifadf.outfield, subset = train.outfield, importance = TRUE, na.action = na.exclude)

#importance(bag.fifadf.outfield)
varImpPlot(bag.fifadf.outfield, n.var = 10)

yhat.bag.outfield <- predict(bag.fifadf.outfield, newdata = fifadf.outfield[-train.outfield, ])
cat('The mean squared error is ', mean((yhat.bag.outfield - fifadf.outfield.test)^2, na.rm = TRUE))

```


```{r LinearModel Gk}
#LinearModel gk

lm.fifadf.gk <- lm(Overall ~ . -(Value), data = subset(fifadf.gk, select = -c(PositionGroup)), subset = train.gk, 
            na.action = na.omit)
yhat.lm.gk <- predict(lm.fifadf.gk, newdata = fifadf.gk[-train.gk, ])
cat('The mean squared error is ', mean((yhat.lm.gk - fifadf.gk.test)^2, na.rm = TRUE))
sort(coef(lm.fifadf.gk), decreasing = TRUE)[1:10] #sorted list of top 10 coefficients
```


```{r LinearModel Outfield}
#LinearModel outfield

lm.fifadf.outfield <- lm(Overall ~ . -(Value), data = subset(fifadf.outfield, select = -c(PositionGroup)), 
                         subset = train.outfield, na.action = na.omit)
yhat.lm.outfield <- predict(lm.fifadf.outfield, newdata = fifadf.outfield[-train.outfield, ])
cat('The mean squared error is ', mean((yhat.lm.outfield - fifadf.outfield.test)^2, na.rm = TRUE))
sort(coef(lm.fifadf.outfield), decreasing = TRUE)[1:10] #sorted list of top 10 coefficients
```



